name: Node.js CI

on:
  push:
    branches: [main]

permissions:
  contents: write

env:
  TAG: 1.1.40

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      # Step 3: Install dependencies
      - name: Install dependencies
        run: make install

      # Step 4: Run linting
      #- name: Run linting
      #  run: make lint

      # Step 5: Run tests
      #- name: Run tests
      #  run: make test

      # Step 6: Docker login to DockerHub
      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 7: Docker build and push (with dynamic image tag)
      - name: Docker build and push
        run: |
          TAG=${{ env.TAG }}
          docker build -t ${{ secrets.DOCKERHUB_REPO }}/nodeproject:${TAG} .
          docker push ${{ secrets.DOCKERHUB_REPO }}/nodeproject:${TAG}



#docker run -d -p 3000:3000 --name $CONTAINER_NAME rajeshecb70/nodeproject:${TAG}



      # Step 8: Deployment
      - name: SSH into local server using password
        run: |
          # Install sshpass to handle password-based SSH login
       #   sudo apt-get install -y sshpass
	docker run -d -p 3000:3000 --name NodeProject $(DOCKERHUB_REPO)/nodeproject:$(TAG)
